name: Clonar subm贸dulos privados

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do reposit贸rio com subm贸dulos
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_TOKEN }}

      - name: Teste
        run: echo "Subm贸dulos clonados com sucesso!"
